project:
  type: website
  output-dir: docs


website:
  page-footer:
    center: 
      - text: "Copyright © 2023 JeongJune Moon. All Rights Reserved."
      
  search:
   location: navbar
   type: overlay

  navbar:
    logo: "images/kapoor.jpg"
    href: index.qmd

    
    # left:
    #   - text: JeongJune Moon
    #     href: index.qmd

        
    right:
      - text: ABOUT
        menu: 
          - text: Education
            href: Education.qmd
            
          - text: Curriculum Vitae
            href: resume.qmd
            
      - text: RESEARCH
        menu: 
          - text: Publications
            href: Publications.qmd
          - text: Projects  
            href: projects.qmd
            
      - text: PHOTOGRAPHY
        href: Photography.qmd
      

format:
  html:
    theme: theme.scss

css:
  - styles.css
  - lightbox.css



