project:
  type: website
  output-dir: docs

website:
  search:
   location: navbar
   type: overlay

  navbar:
    logo: "images/kapoor.jpg"
    href: index.qmd

    
    # left:
    #   - text: JeongJune Moon
    #     href: index.qmd

        
    right:
      - text: ABOUT
        menu: 
          - text: Research Interest
            href: research_interest.qmd
            
          - text: Curriculum Vitae
            href: resume.qmd
      - href: projects.qmd
        text: PROJECTS

format:
  html:
    theme: theme.scss
    css: styles.css


